/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Block5: typeof import('./src/components/block5/block5.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    MyDraggable: typeof import('./src/components/myDraggable2/myDraggable.vue')['default']
  }
}
